config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.sitemaps.views import sitemap
from consignment.sitemaps import PackageSitemap, StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'packages': PackageSitemap,
}

from django.conf import settings
from django.conf.urls.static import static

app = 'consignment'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),


    path('', include('consignment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

consignment/urls.py
from django.urls import path
from . import views

app_name = 'track'

urlpatterns = [
    path('', views.track_package, name='track_package'),
    #path('track/', views.track_package, name='track_package'),
    path('package/<str:package_id>/', views.package_detail, name='package_detail'),
    path('receipt/<str:package_id>/', views.generate_pdf, name='generate_pdf'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('cookies-policy/', views.cookies_policy, name='cookies_policy'),
    path('shipping-policy/', views.shipping_policy, name='shipping_policy'),
    path('returns-policy/', views.returns_policy, name='returns_policy'),
]

urls.py
from django.conf.urls import handler404, handler500
from django.urls import path
from . import views

urlpatterns = [
    # ... your url patterns here ...
]

handler404 = 'consignment.views.custom_404_view'
handler500 = 'consignment.views.custom_500_view'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Package Tracking System{% endblock %}</title>
    {% block extracss %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}
</head>

<body>
    <header class="header">
        <div class="container text-center">
            <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo">
            <h1 class="title-text">PACKAGE PULSE</h1>
        </div>
    </header>
    <main class="container mt-5">
        {% block content %}{% endblock %}
    </main>
    <footer class="footer">
        <div class="footer text-center">
            <p>&copy; 2024 Package Tracking System. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>

templates/track_package.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Track Package - Package Tracking System{% endblock %}
{% block content %}
<div class="tracking-container">
    <h1 class="text-center">Track Your Package</h1>
    <form method="post" action="{% url 'track:track_package' %}" class="tracking-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="tracking_number" class="form-label">Enter Tracking Code</label>
            <input type="text" class="form-control" id="tracking_number" name="tracking_code" required>
        </div>
        <div class="form-group text-center mt-3">
            <button type="submit" class="btn btn-primary">Track</button>
        </div>
    </form>
    {% if error_message %}
        <div class="alert alert-danger mt-3" role="alert">{{ error_message }}</div>
    {% endif %}
    <section class="promo-section">
        <div class="footer text-center">
            <h2>Track Your Packages in Over 220 Countries 🌎</h2>
        </div>
    </section>
    
</div>
{% endblock %}